# Generated by Django 5.0.6 on 2024-07-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('batch', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
