# Generated by Django 5.0.6 on 2024-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_subject_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='c_language_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='cd_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='dbms_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='ds_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='it_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='java_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='os_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='python_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='r_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='wt_attendance',
            field=models.IntegerField(default=0),
        ),
    ]
