# Generated by Django 5.0.6 on 2024-07-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_session_ip_address_session_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='department',
            name='subjects',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='current_semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
