# Generated by Django 5.0.6 on 2024-07-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_session_subject_alter_student_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
