# Generated by Django 5.0.6 on 2024-07-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_session_subject_alter_student_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
        migrations.AddField(
            model_name='semester',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='monitoring.department'),
        ),
        migrations.AlterField(
            model_name='session',
            name='current_semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='monitoring.semester'),
        ),
    ]
