# Generated by Django 5.0.6 on 2024-08-01 17:23

import django.db.models.deletion
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[monitor.models.validate_roll_no])),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('year', models.CharField(default='2024-28', max_length=10)),
                ('batch', models.CharField(default='A', max_length=5)),
                ('c_language_attendance', models.IntegerField(default=0)),
                ('it_attendance', models.IntegerField(default=0)),
                ('ds_attendance', models.IntegerField(default=0)),
                ('os_attendance', models.IntegerField(default=0)),
                ('java_attendance', models.IntegerField(default=0)),
                ('dbms_attendance', models.IntegerField(default=0)),
                ('python_attendance', models.IntegerField(default=0)),
                ('wt_attendance', models.IntegerField(default=0)),
                ('r_attendance', models.IntegerField(default=0)),
                ('cd_attendance', models.IntegerField(default=0)),
                ('sd_attendance', models.IntegerField(default=0)),
                ('dv_attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_time', models.CharField(choices=[('09:30', '9:30'), ('10:30', '10:30'), ('12:00', '12:00'), ('14:00', '2:00'), ('15:00', '3:00')], max_length=5)),
                ('out_time', models.CharField(choices=[('10:30', '10:30'), ('11:30', '11:30'), ('13:00', '1:00'), ('15:00', '3:00'), ('16:00', '4:00')], max_length=5)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.subject')),
            ],
        ),
    ]
