# Generated by Django 5.0.6 on 2024-08-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lab',
            field=models.CharField(blank=True, choices=[('Lab-1', 'Lab-1'), ('Lab-2', 'Lab-2'), ('Lab-3', 'Lab-3'), ('Lab-4', 'Lab-4')], max_length=10, null=True),
        ),
    ]
